### ISSUE TITLE
我的action執行不成功，求助

### ISSUE THREAD

**Issue by lewis1573** [onejar99/demo-build-and-publish-gitbook#2]
您好，我參考您的代碼做了一個workflow，去年可以工作，但是我今天 發現action一直無法成功，從log來看，好像是anchor-navigation-ex插件的問題，你那裡能正常工作嗎？

[我的action](https://github.com/lewis1573/SystemVerilog-for-Verification-Third-Edition-cn/actions)

**Comment by onejar99** [comment]
@lewis1573 謝謝你的回報，我測試確實也不行，檢查後發現是 anchor-navigation-ex plugin 拉到新版 dependency 後有相容性問題。

已經 workaround 修復一版 v1.0.2，我測試 ok，歡迎升級試試看：
https://github.com/lewis1573/SystemVerilog-for-Verification-Third-Edition-cn/blob/master/.github/workflows/build.yml#L23

**Comment by lewis1573** [comment]
已經成功部署了，非常感謝！
